[package]
name = "gui-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.7.0"
crossterm = "0.26.1"
newsapi = {version = "0.1.0", path = "./newsapi"}
termimad = "0.23.0"
